baseURL: "https://rikkyarisendi.github.io/"
title: Rikky Arisendi
paginate: 5

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

googleAnalytics: 

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: Rikky Arisendi | Portofolio
  description: "Typing. . . ."
  keywords: [Blog, Portfolio, PaperMod]
  author: Rikky Arisendi
  # author: ["Me", "You"] # multiple authors
  images: ["<link or path of image for opengraph, twitter-cards>"]
  DateFormat: "January 2, 2006"
  defaultTheme: auto # dark, light
  disableThemeToggle: false

  ShowReadingTime: true
  ShowShareButtons: true
  ShareButtons: ["linkedin", "facebook", "whatsapp", "twitter", "buymeacoffee"]
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: false
  ShowWordCount: false
  ShowRssButtonInSectionTermList: false
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false

  assets:
    # disableHLJS: true # to disable highlight.js
    # disableFingerprinting: true
    favicon: "/images/fav.png"
    favicon16x16: "/images/fav.png"
    favicon32x32: "/images/fav.png"
    apple_touch_icon: "/images/fav.png"
    safari_pinned_tab: "/images/fav.png"

  label:
    text: "Rikky Arisendi"
    icon: /apple-touch-icon.png
    iconHeight: 35

  # profile-mode
  profileMode:
    enabled: true # needs to be explicitly set
    title: "Hello, I'm Rikky...👋"
    subtitle: "Graphic & Web Designer"
    imageUrl: "/images/profile.png"
    imageWidth: 250
    imageHeight: 250
    imageTitle: 
    buttons:
      - name: Posts
        url: "#"
      - name: Tags
        url: "#"

  socialIcons:
    - name: twitter
      url: "https://twitter.com/"
    - name: instagram
      url: "https://instagram.com/"
    - name: linkedin
      url: "https://linkedin.com/"
    - name: github
      url: "https://github.com/"

  analytics:
    google:
      SiteVerificationTag: "XYZabc"
    bing:
      SiteVerificationTag: "XYZabc"
    yandex:
      SiteVerificationTag: "XYZabc"

  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: true # hide on single page

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]
menu:
  main:
    - identifier: Home
      name: Home
      url: //
      weight: 10
    - identifier: About
      name: About
      url: /about/
      weight: 20
    - identifier: Blog
      name: Blog
      url: /blog/
      weight: 30
    - identifier: Projects
      name: Projects
      url: /projects/
      weight: 40
    - identifier: Docs
      name: Docs
      url: /docs/
      weight: 50


pygmentsUseClasses: true
markup:
  highlight:
    noClasses: false
    # anchorLineNos: true
    # codeFences: true
    # guessSyntax: true
    # lineNos: true
    # style: monokai
